# This is a basic workflow to help you get started with Actions

name: terraform

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  terraform:
    name: 'Terraform'
    env:
     ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
     ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
     ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
     ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 3.51.0
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: "./terraform"
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 3.51.0
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: "./terraform"
  
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 3.51.0
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: "./terraform"
          
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 3.51.0
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: "./terraform"
  
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 3.51.0
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: "./terraform"


      
